apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
      protocol: TCP